sony/flutter-embedded-linux

- README.md
Update README.
@Mai-Matsuura 
May I request you to review?
> slightly update README

- README.md
I added the description and the link of Flutter SDK to build linux apps.
> Add description of Flutter SDK to build linux apps

- README.md
- examples/flutter-drm-backend/README.md
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.cc
I changed the setting method of the DRM device filename from the fixed value to the environment variable.
> Change setting method of the DRM device filename.

- src/flutter/shell/platform/linux_embedded/surface/context_egl.h
- src/flutter/shell/platform/linux_embedded/surface/linuxes_surface_gl_drm.h
- src/flutter/shell/platform/linux_embedded/surface/linuxes_surface_gl_wayland.h
I changed the output log level of the process off-screen from error to warning. Because the off-screen surface is not mandatory, but it affects graphics performance.
```
[ERROR][context_egl.h(95)] Failed to create EGL off-screen surface.(eglGetError: EGL_BAD_ALLOC)
[ERROR][linuxes_surface_gl_drm.h(50)] Off-Screen surface is invalid.
```
- https://github.com/sony/flutter-embedded-linux/issues/4
> Change output log level when the off-screen surface creation failed

- src/flutter/shell/platform/embedder/embedder.h
Update [embedder.h](https://github.com/flutter/engine/blob/master/shell/platform/embedder/embedder.h) to the latest version. 
@Mai-Matsuura I'm sorry but could you check if operating correctly with this change and the latest `libflutter_engine.so`?
> Update embedder.h to the latest version

- src/flutter/shell/platform/linux_embedded/plugin/key_event_plugin.h
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.h
Including `unordered_map`' is missing.
> However I got some compilation errors due to wrongly set includes when building directly on the Pi. I use clang12 built from meta-clang into the raspberrry image. Error was about unordered_map includes missing in at least one header file (key_event_plugin.h). But building the source cross from yocto didn't throw that error but for my understanding it has to be fixed.
- https://github.com/sony/flutter-embedded-linux/issues/4
> unordered_map header file is missing

- BUILDING-ENGINE-EMBEDDER.md
- README.md
I added the supplement to install libflutter_engine.so and run Flutter app. See also: https://github.com/sony/flutter-embedded-linux/issues/24
> [README] Add supplement to install libflutter_engine.so and run Flutter app

- src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.cc
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.h
The Flutter engine asserts that it receives an event from a different thread than the main thread. (This feature is valid only in debug mode)  
On the DRM backend, a sub-thread was created to receive the libinput event.  This was the cause of this issue.
I fixed it to receive the libinput event on the main thread.
I verified that the DRM backend works in debug mode on x64 Ubuntu and Raspberry Pi4.
#33
> Fix debug mode not working on the DRM backend.

- .github/workflows/build-test.yml
- src/flutter/shell/platform/linux_embedded/surface/context_egl.h
- src/flutter/shell/platform/linux_embedded/surface/context_egl_drm.h
- src/flutter/shell/platform/linux_embedded/surface/context_egl_wayland.h
- src/flutter/shell/platform/linux_embedded/surface/linuxes_surface.h
- src/flutter/shell/platform/linux_embedded/surface/linuxes_surface_gl_drm.cc
- src/flutter/shell/platform/linux_embedded/surface/linuxes_surface_gl_drm.h
- src/flutter/shell/platform/linux_embedded/surface/linuxes_surface_gl_wayland.cc
- src/flutter/shell/platform/linux_embedded/surface/linuxes_surface_gl_wayland.h
- src/flutter/shell/platform/linux_embedded/surface/native_window.h
- src/flutter/shell/platform/linux_embedded/surface/native_window_drm.cc
- src/flutter/shell/platform/linux_embedded/surface/native_window_drm.h
- src/flutter/shell/platform/linux_embedded/surface/native_window_wayland.h
Refactor source files before adding X11 backend support. I needed to specify the dummy variable type (`gbm_surface`) in the DRM backend when I use the common template even though `Surface` in `native_window.h` is only used by the Wayland backend.
In addition, I fixed the following GitHub Actions error.
```
Err:24 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libsystemd-dev amd64 245.4-4ubuntu3.4
404  Not Found [IP: 40.119.46.219 80]
Err:25 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libudev-dev amd64 245.4-4ubuntu3.4
404  Not Found [IP: 40.119.46.219 80]
Get:26 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libwacom-bin amd64 1.3-2ubuntu1 [5484 B]
Get:27 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libwacom-dev amd64 1.3-2ubuntu1 …
```
> Refactor native window template

- src/flutter/shell/platform/linux_embedded/surface/native_window_x11.cc
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_x11.cc
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_x11.h
I added mouse events support on x11.
- https://github.com/sony/flutter-embedded-linux/issues/37
> Add mouse events support on x11

- .github/workflows/build-test.yml
- BUILDING-ENGINE-EMBEDDER.md
- DEBUGGING.md
- README.md
- cmake/build.cmake
I've changed the following things.
- Added how to debug Flutter apps into README
- Changed Flutter engine library path at build time
- https://github.com/sony/flutter-embedded-linux/issues/24
> Update debugging readme and change Flutter engine library path at build time

- DEBUGGING.md
- README.md
- cmake/build.cmake
- examples/flutter-drm-backend/cmake/user_build.cmake
- examples/flutter-external-texture-plugin/cmake/user_build.cmake
- examples/flutter-wayland-client/cmake/user_build.cmake
- examples/flutter-weston-desktop-shell-virtual-keyboard/cmake/user_build.cmake
- examples/flutter-weston-desktop-shell/cmake/user_build.cmake
- examples/flutter-x11-client/cmake/user_build.cmake
I've changed that `FLUTTER_RELEASE` is changed in conjunction with `CMAKE_BUILD_TYPE`.
e.g.
```
$ cmake -DUSER_PROJECT_PATH=examples/flutter-x11-client -DCMAKE_BUILD_TYPE=Debug ..
$ cmake --build .
$ FLUTTER_ENGINE_SWITCHES=2 \
FLUTTER_ENGINE_SWITCH_1="observatory-port=12345"  \
FLUTTER_ENGINE_SWITCH_2="disable-service-auth-codes" \
./flutter-x11-clinet sample/build/linux/x64/debug/bundle
```
- https://github.com/sony/flutter-embedded-linux/issues/50
> Support debug mode

- BUILDING-ENGINE-EMBEDDER.md
- README.md
I updated README to add the description to get the engine version from Flutter SDK which currently using.
> Update README: Added description to get engine version from flutter sdk

- src/flutter/shell/platform/linux_embedded/logger.cc
- src/flutter/shell/platform/linux_embedded/plugin/key_event_plugin.cc
- src/flutter/shell/platform/linux_embedded/plugin/key_event_plugin_glfw_util.cc
- src/flutter/shell/platform/linux_embedded/plugin/mouse_cursor_plugin.cc
- src/flutter/shell/platform/linux_embedded/plugin/platform_plugin.cc
- src/flutter/shell/platform/linux_embedded/plugin/text_input_plugin.cc
I refactored some files to use unnamed namespace instead of static except for the code files around window/surface which are working on currently.
> Refactoring: use unnamed namespace instead of static

- src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.h
I removed the keywords of static and struct, and changed the struct name from cursor_info to CursorInfo.
> Refactoring: remove the keywords of static and struct

- doc/README.md
I updated doc/README.md and fixed the mistake in installing libflutter_engine.so.
> Update doc/README: Fix incorrect install path

- src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.cc
I fixed the color format value because the value specified in `gbm_surface_create` was incorrect.  I don't know why but it worked on RPI4 etc.
See: https://www.khronos.org/registry/EGL/extensions/MESA/EGL_MESA_platform_gbm.txt
- https://github.com/sony/flutter-embedded-linux/issues/4
> Fix GBM color format

- README.md
I updated the description of DRM-GBM backend for i.mx 8m devices in README. i.MX 8M doesn't support EGL on GBM. So, Flutter embedder with DRM-GBM backend will not work on these devices.
> Update README: the note of DRM for i.mx 8m devices

- src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.h
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.h
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_x11.h
`binding_handler_delegate_` isn't initialized to null. If a window event happens before setting `binding_handler_delegate_`, the embedder will crash.
> Initialize binding_handler_delegate_ to null

- src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.cc
- src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.h
- src/flutter/shell/platform/linux_embedded/plugin/key_event_plugin.cc
- src/flutter/shell/platform/linux_embedded/plugin/key_event_plugin.h
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.h
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_x11.cc
- src/flutter/shell/platform/linux_embedded/window_binding_handler_delegate.h
I deleted FLUTTER_LINUXES_BUTTON_DOWN and FLUTTER_LINUXES_BUTTON_UP defines, and replaced these into simple bool var.
> Refactoring: delete FLUTTER_LINUXES_BUTTON_* defines

- cmake/build.cmake
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.h
I added text-input-protocol-v3 for onscreen keyboards on Wayland compositors. Currently, Weston doesn't still support v3. On the other hand, other compositors have switched from v1 to v2 or v3. I think we need to support both of them now.
- https://github.com/sony/flutter-embedded-linux/issues/108
- https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/150
> Support text input protocol v3 for onscreen keyboards on Wayland

- src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.h
I renamed `CursorInfo::wl_pointer` to `CursorInfo::pointer` to avoid build error in some toolchains.
See: https://github.com/sony/flutter-embedded-linux/issues/121
> Rename wl_pointer in CursorInfo

- doc/building-engine-embedder.md
I updated README for building-flutter-engine and added `disable-desktop-embeddings` option.
> Update README: add disable-desktop-embeddings option

- src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.h
I fixed the following bug.
See: https://github.com/sony/flutter-embedded-linux/issues/108#issuecomment-845544970
> Some additional observations:
If the user switches from the Flutter Wayland application with the onscreen keyboard opened, the keyboard will behave as expected (close or remain opened).
However when the user returns back to the Flutter app, the text field appears to have the focus (cursor is blinking) but the onscreen keyboard will be closed.
To bring the onscreen keyboard again - lose focus from the input field and tap on it again or focus on a different input field.
> Fixed bug regarding the display of Wayland's on-screen keyboard

- doc/building-engine-embedder.md
- meta-flutter/recipes-graphics/flutter-engine/flutter-engine.bb
I updated `.gclinet` file to not download other than Linux dependent libraries. This change helps speed up build tasks of Flutter Engine.
> Update .gclient file to not download other than Linux deps

- cmake/build.cmake
- src/flutter/shell/platform/linux_embedded/flutter_linuxes.cc
- src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.cc
- src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.h
- src/flutter/shell/platform/linux_embedded/plugins/platform_views_plugin.cc
- src/flutter/shell/platform/linux_embedded/plugins/platform_views_plugin.h
- src/flutter/shell/platform/linux_embedded/public/flutter_platform_views.h
I added the first implementation of the platform views plugin. However, it isn't completed yet such as touch, resize, and so on.
- https://github.com/sony/flutter-embedded-linux/issues/41
> Add platform views plugin as a first implementation

- .github/workflows/build-test.yml
I changed the downloading path of the pre-build Flutter Engine in the CI because we cannot download `libflutter_engine.so` for Linux x64 from the Google infra server.
> Change the downloading path of pre-build Flutter Engine in the CI

- src/flutter/shell/platform/linux_embedded/window/native_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/native_window_wayland.h
Fixed https://github.com/sony/flutter-embedded-linux/issues/163
Cause: https://github.com/sony/flutter-embedded-linux/commit/2cd2fbc2f9bd5e64723c0b31871488374961ef04
I tested this change on i.mx 8m mini board.
> Bugfix offscreen surface for wayland

- .github/workflows/build-test.yml
I changed the download path of libflutter_engine.so.
- https://github.com/sony/flutter-embedded-linux/issues/141
> Change download path in CI/CD workflow

- cmake/build.cmake
I fixed the link error of libflutter_elinux_*.so.
> Fix link error of libflutter_elinux_*.so

- CMakeLists.txt
- cmake/build.cmake
I added `FLUTTER_RELEASE` cmake option to separate it from `CMAKE_BUILD_TYPE`.
> Add FLUTTER_RELEASE CMake option

- src/flutter/shell/platform/common/client_wrapper/standard_codec.cc
See: https://github.com/flutter/engine/commit/2fa5f698a3a33ff1a82da5b002a4d93f50db1b04
> Merge the latest version from engine repo (08162021)

- src/flutter/shell/platform/linux_embedded/flutter_elinux_view.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux_view.h
- src/flutter/shell/platform/linux_embedded/window_binding_handler_delegate.h
I fixed the touch-input bug in https://github.com/sony/flutter-embedded-linux/issues/127, which caused by the wrong time unit.
- Wayland: milliseconds (https://wayland-book.com/seat/touch.html#touch-and-release)
- DRM (GBM/EGLStream): milliseconds (libinput_event_touch_get_time)
- Flutter Engine: microseconds (https://github.com/flutter/engine/blob/master/shell/platform/embedder/embedder.h#L651)
See: https://github.com/sony/flutter-embedded-linux/issues/127#issuecomment-914054958
Thanks a lot, @anyuliu
(cc @jcviau)
> Fix wrong touch input

- src/flutter/shell/platform/linux_embedded/surface/elinux_egl_surface.cc
Currently, the embedder always waits for the next Vsync when flutter calls `eglSwapBuffers`.
Fixed https://github.com/sony/flutter-embedded-linux/issues/220
> Fix synchronized frame on Wayland

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
1. Run a flutter app with the window decorations on Weston 8.0
2. Press the maximize button
```
[15:42:27.378] libwayland: error in client communication (pid 20431)
xdg_wm_base@11: error 4: xdg_surface buffer does not match the configured state
```
I'm not sure, but this issue doesn't happen on Gnome Wayland.
> [wayland] Fix crashes with `xdg_surface buffer does not match the configured state`

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.h
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decorations_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decorations_wayland.h
- Add restore original window size support (unset maximize-window)
- Fix the window decorations will be hidden after pressing the max-button
- https://github.com/sony/flutter-embedded-linux/issues/6
> [wayland] Fix operations of the max button in the window decorations

- src/flutter/shell/platform/linux_embedded/surface/elinux_egl_surface.cc
Reverted #221 (disabled by default)
See also:
- https://github.com/sony/flutter-embedded-linux/issues/230
- https://github.com/sony/flutter-embedded-linux/issues/234
> Revert: Fix synchronized frame on Wayland (#221)

- src/client_wrapper/flutter_view_controller.cc
- src/flutter/shell/platform/linux_embedded/public/flutter_elinux.h
Renamed `FlutterDesktopViewMode` enum value to avoid conflict with the latest `embedder.h`
> Rename enum value of FlutterDesktopViewMode

- src/flutter/shell/platform/common/client_wrapper/include/flutter/event_channel.h
Merged https://github.com/flutter/engine/pull/36882
> Merge common source file from flutter/engine

- AUTHORS
- cmake/build.cmake
- src/flutter/shell/platform/common/client_wrapper/include/flutter/string_message_codec.h
- src/flutter/shell/platform/common/client_wrapper/string_message_codec.cc
- src/flutter/shell/platform/linux_embedded/plugins/lifecycle_plugin.cc
- src/flutter/shell/platform/linux_embedded/plugins/lifecycle_plugin.h
The lifecycle plugin was using a *standard* message codec but it is supposed to be using a *string* message codec.
I haven't found any official documentation about why that's the case  (except for [these](https://github.com/flutter/engine/blob/8f2221fbef28b478debb78dd233f5250b220ca99/shell/platform/darwin/common/framework/Headers/FlutterCodecs.h#L58-L60) code [comments](https://github.com/flutter/engine/blob/8f2221fbef28b478debb78dd233f5250b220ca99/shell/platform/android/io/flutter/plugin/common/StringCodec.java#L14-L16)) but that's how it is currently implemented for both [iOS](https://github.com/flutter/engine/blob/8f2221fbef28b478debb78dd233f5250b220ca99/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L572) and [Android](https://github.com/flutter/engine/blob/8f2221fbef28b47 …
> Use string message codec for lifecycle plugin

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.h
The previous logic contained a hard-coded cursor theme size of `32` pixels and the cursor surface buffer scale was never configured (so it defaulted to a value of `1`). This meant the cursor theme was blurry on HighDPI screens.
This pull-request attempts to fix that by:
- change the logic to replace the single instance of the cursor theme with an array of themes (one for each output scale factor)
- delay loading the theme until a cursor needs to be shown in order to make sure the correct theme size is loaded
- replace hard-coded cursor size with the value from the `XCURSOR_SIZE` environment variable (*if* it has set)
- change the default cursor size (e.g.: when `XCURSOR_SIZE` is not set) from `32` to `24` pixels (this value was [copied from …
> Add support for HighDPI cursor themes

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
Clear the current cursor name when leaving the window in order to make sure it gets redrawn the next time it enters the window.
This is necessary due to this bit of logic which skips drawing the cursor if it hasn't changed since the last time it was drawn:
https://github.com/sony/flutter-embedded-linux/blob/df0d3fc545b7656e3c0242c23dc4bb3d29c30ea3/src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc#L1201-L1203
https://user-images.githubusercontent.com/433598/208247802-5eaeeab6-8e9f-42dd-b4d9-45a49cb2bdc6.mp4
https://user-images.githubusercontent.com/433598/208247811-149f2c6e-683e-489d-8a09-cd4d0116e54b.mp4
> Redraw cursor when re-entering window

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.h
The previous logic was using the scale factor of the last received [ouput scale event](https://wayland.app/protocols/wayland#wl_output:event:scale) as the [window's current scale factor](https://github.com/sony/flutter-embedded-linux/blob/9dd66b9cb69bbfea0bcc39fda10cead94ec4ec5b/src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc#L1030-L1032) which was incorrect (and non-deterministic). This pull-request attempts to fix that by using the *largest* scale factor of the window's list of [entered outputs](https://wayland.app/protocols/wayland#wl_surface:event:enter).
> **Note**
>
> There will be some follow-up pull-requests that will try to fix various issues related to HighDPI (and mixed-DPI) support.
I agree to delegate all rights related to this PR to Sony.
> Use scale factor from the window's list of entered outputs

- src/flutter/shell/platform/linux_embedded/window/renderer/window_decorations_wayland.cc
Fix small typo which was causing a negative height value to be passed to the button resize method.
> Use positive height for button resize argument

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
The previous code stopped listening for presentation feedback events as soon as a discarded event was received.
When this happened, the client-side decorations stopped being redrawn and got "stuck". This broken state could be consistently reproduced on sway when resizing the window using $mod key + mouse right click (see screen recordings below).
[before.webm](https://user-images.githubusercontent.com/433598/209867850-54b1823a-ae51-4d15-b081-af767e7598ae.webm)
[after.webm](https://user-images.githubusercontent.com/433598/209867875-0616b0a3-3c2a-467b-bca5-5ba2b5812ec6.webm)
This pull-request fixes that by continuing to listen to presentation feedback events after `discarded` events.
> Continue listening for presentation feedback events after discarded frame

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
The previous logic contained a bug related to the cursor hotspot coordinates which made the cursor "jump" around when entering and leaving the window surface (see screen recordings below).
[before.webm](https://user-images.githubusercontent.com/433598/209983736-cd33733b-a84d-4b66-b412-ed286afebbd0.webm)
[after.webm](https://user-images.githubusercontent.com/433598/209983730-2d1632cc-656c-446d-b6cb-1d93e99edc42.webm)
This pull-request fixes that by dividing the hotspot by the scaling factor.
> Fix cursor hotspot for scale factors different than 1

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.h
When client decorations are enabled the Flutter surface size should be equal to window height minus the client decorations height.
Without this change the content at the bottom of the Flutter surface could get "cropped" when client decorations are enabled.
> Subtract client decorations height from flutter surface height

- src/flutter/shell/platform/linux_embedded/flutter_elinux_view.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux_view.h
- src/flutter/shell/platform/linux_embedded/surface/surface_base.cc
- src/flutter/shell/platform/linux_embedded/surface/surface_base.h
- src/flutter/shell/platform/linux_embedded/surface/surface_decoration.cc
- src/flutter/shell/platform/linux_embedded/surface/surface_decoration.h
- src/flutter/shell/platform/linux_embedded/window/elinux_window.h
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.h
- src/flutter/shell/platform/linux_embedded/window/native_window.h
- src/flutter/shell/platform/linux_embedded/window/native_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/native_window_wayland.h
- src/flutter/shell/platform/linux_embedded/window/native_window_wayland_decoration.cc
- src/flutter/shell/platform/linux_embedded/window/native_window_wayland_decoration.h
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decoration.h
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decoration_button.cc
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decoration_button.h
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decoration_titlebar.cc
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decoration_titlebar.h
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decorations_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decorations_wayland.h
- src/flutter/shell/platform/linux_embedded/window_binding_handler.h
- src/flutter/shell/platform/linux_embedded/window_binding_handler_delegate.h
> **Warning**
> 
> There are still parts of the code-base which are missing these annotations and would benefit from them. Therefore, this pull-request should be seen more like a starting point for this work.
This pull-request should contain **no functional changes**. It is only meant to annotate various methods and attributes with explicit information about whether logical or physical pixels are being used.
The current usage patterns have been used to determine whether to mark existing code as dealing with physical or logical coordinates.
This is part of a larger set of changes that are meant to add HighDPI support for Wayland.
The `_px` and `_dip` suffixes are sometimes used for variables depending on whether their data represents physical or logical pixels respectively. Obviously, this …
> Annotate code with coordinate system information

- src/flutter/shell/platform/linux_embedded/public/flutter_elinux.h
- src/flutter/shell/platform/linux_embedded/window/elinux_window.h
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/native_window_wayland_decoration.cc
- src/flutter/shell/platform/linux_embedded/window/native_window_wayland_decoration.h
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decoration.h
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decoration_button.cc
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decoration_button.h
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decoration_titlebar.cc
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decoration_titlebar.h
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decorations_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/renderer/window_decorations_wayland.h
> **Warning**
>
> This pull-request is currently marked as a draft because it depends on a couple of pull-requests which haven't been merged yet: #311, #312, #313.
This pull-request contains various fixes related to HighDPI support on Wayland. Most of the fixes involve using the current window scale where needed and keeping the buffer scale in sync with the window scale.
The screen recordings below show a basic app before and after these fixes. The most notable difference is getting rid of the blurriness and the oversized widgets when running on a HighDPI screen on Wayland.
[before.webm](https://user-images.githubusercontent.com/433598/210018288-5a1d95ed-0727-42f8-b674-e361300f3d5f.webm)
[after.webm](https://user-images.githubusercontent.com/433598/210018287-464de543-6a89-460d-a385-790addb …
> Add initial support for HighDPI on Wayland

- examples/flutter-drm-eglstream-backend/flutter_embedder_options.h
- examples/flutter-drm-eglstream-backend/main.cc
- examples/flutter-drm-gbm-backend/flutter_embedder_options.h
- examples/flutter-drm-gbm-backend/main.cc
- examples/flutter-external-texture-plugin/flutter_embedder_options.h
- examples/flutter-external-texture-plugin/main.cc
- examples/flutter-video-player-plugin/flutter_embedder_options.h
- examples/flutter-video-player-plugin/main.cc
- examples/flutter-wayland-client/flutter_embedder_options.h
- examples/flutter-wayland-client/main.cc
- examples/flutter-x11-client/flutter_embedder_options.h
- examples/flutter-x11-client/main.cc
- src/client_wrapper/flutter_view_controller.cc
- src/client_wrapper/include/flutter/flutter_view_controller.h
- src/flutter/shell/platform/linux_embedded/public/flutter_elinux.h
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
Remove the [hard-coded "Flutter" window title](https://github.com/sony/flutter-embedded-linux/blob/d88c3c55d9bce06a864f5b51a6d5a9a71293a336/src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc#L1198) on Wayland and make it configurable as part of the `ViewProperties`. Also, add support for configuring the [window's app ID](https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_app_id) too.
Currently these properties are only used on Wayland but it may make sense to use them for X11 too (but that's not part of this pull-request).
> Make window title and app ID configurable

- src/flutter/shell/platform/linux_embedded/window/renderer/window_decoration_button.cc
This pull-request sets the GL viewport for the window decoration buttons. This is necessary because otherwise the buttons are not drawn correctly when moving the window between outputs with different scale factors.
As an example of this issue see the screen recordings below where the output on the right (visible in the recording) has a scale factor of 1 and the output on the left (**not** visible in the recording) has a scale factor of 2.
[before.webm](https://user-images.githubusercontent.com/433598/210281792-5396db7d-5a41-4e3c-bfba-52730c51e62f.webm)
[after.webm](https://user-images.githubusercontent.com/433598/210281430-2941a453-e62b-433d-8cc0-1077048514cf.webm)
> Set decoration button GL viewport to fix resize issues

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
The previous logic was ignoring most of the toplevel `configure` events *unless* the window was maximized or was being resized. This pull-request removes that check in order to always respect the size suggested by the compositor.
This is particularly important for tiling compositors (e.g.: sway) where the window can be arbitrarily resized by the compositor even when it's not maximized (e.g.: when it's part of a tiled layout). The screen recordings below show some comparison videos of the old and new behavior.
Please review this carefully because it's not very clear what was the *original* purpose of the checks that are being removed in this pull-request. That being said, I have tested the new code in Sway, Weston, GNOME and Hyprland and it does seem to work as expected (as far as I can …
> Wayland: Always respect XDG configure size regardless of state

- AUTHORS
- cmake/build.cmake
- src/flutter/shell/platform/common/client_wrapper/core_implementations.cc
- src/flutter/shell/platform/common/client_wrapper/include/flutter/texture_registrar.h
- src/flutter/shell/platform/common/public/flutter_texture_registrar.h
- src/flutter/shell/platform/linux_embedded/external_texture.h
- src/flutter/shell/platform/linux_embedded/external_texture_egl_image.cc
- src/flutter/shell/platform/linux_embedded/external_texture_egl_image.h
- src/flutter/shell/platform/linux_embedded/flutter_elinux_texture_registrar.cc
Hello.
I needed to add EGLImage-based texture support to flutter-embedded-linux to improve video_player playback performance.
So I added support.
Relevant issue: sony/flutter-elinux-plugins#64
> Add support EGLImage-based texture

- CMakeLists.txt
- cmake/build.cmake
- src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux_view.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux_view.h
- src/flutter/shell/platform/linux_embedded/surface/egl_utils.cc
- src/flutter/shell/platform/linux_embedded/surface/egl_utils.h
- src/flutter/shell/platform/linux_embedded/surface/elinux_egl_surface.cc
- src/flutter/shell/platform/linux_embedded/surface/elinux_egl_surface.h
- src/flutter/shell/platform/linux_embedded/surface/surface_base.cc
- src/flutter/shell/platform/linux_embedded/surface/surface_decoration.cc
- src/flutter/shell/platform/linux_embedded/surface/surface_decoration.h
- src/flutter/shell/platform/linux_embedded/surface/surface_gl.cc
- src/flutter/shell/platform/linux_embedded/surface/surface_gl.h
- src/flutter/shell/platform/linux_embedded/surface/surface_gl_delegate.h
> add dirty region management

- AUTHORS
- src/flutter/shell/platform/linux_embedded/window/native_window_drm.cc
- src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.cc
In RK3399 board running latest mainline kernel, when the system just booted up, there's no encoder attached to connector, and no crtc attached to encoder. In this case flutter-embedded will fail to start with error message `Couldn't find any encoders`. In this case, `modetest` will report the following:
```
Encoders:
id      crtc    type    possible crtcs  possible clones
38      0       DSI     0x00000001      0x00000001
Connectors:
id      encoder status          name            size (mm)       modes   encoders
39      0       connected       DSI-1           95x53           1       38
```
After the user run something like `glmark2-es2-drm`, they will get initialized, and flutter apps will work now:
```
Encoders:
id      crtc    type    possible crtcs  possible clones
38      37      DSI …
```
> Enhancements to initialization code in drm backend

- AUTHORS
- src/client_wrapper/flutter_engine.cc
- src/client_wrapper/flutter_view_controller.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux.cc
- src/flutter/shell/platform/linux_embedded/public/flutter_elinux.h
flutter_elinux.h is a C API, so reference parameters are unavailable. Change FlutterDesktopViewControllerCreate() and FlutterDesktopEngineCreate() to instead take a pointer. Based fix for upstream issue (flutter/engine#25439).
```
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to …
```
> embedder: don't use reference params in C APIs (#345)

- src/flutter/shell/platform/common/public/flutter_messenger.h
- src/flutter/shell/platform/linux_embedded/flutter_elinux.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.h
- src/flutter/shell/platform/linux_embedded/flutter_elinux_state.h
Import locking and reference counting support for FlutterDesktopMessenger from upstream (#345)
> embedder: locking and refcount support in FlutterDesktopMessenger

- src/flutter/shell/platform/linux_embedded/public/flutter_elinux.h
> elinux: fix missing FlutterDesktopPluginRegistrarGetView() header

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
This change fixes a wrong height size when decoration ("-d") option is used.
> wayland: fix wrong height when using decoration option

- src/flutter/shell/platform/linux_embedded/window/elinux_window.h
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
This change fixes the layout issue that is skewed when using decoration option.
Related PR #359
> wayland: fix layout is skewed issue when using decoration option

- src/flutter/shell/platform/linux_embedded/window/renderer/window_decorations_wayland.cc
This change fixes wrong placement of decoration buttons.
e.g.
```
/flutter-client -b bundle/ -d -s 1.2
```
> wayland: fix missing scaling of decoration buttons

- examples/flutter-drm-eglstream-backend/flutter_embedder_options.h
- examples/flutter-drm-eglstream-backend/main.cc
- examples/flutter-drm-gbm-backend/flutter_embedder_options.h
- examples/flutter-drm-gbm-backend/main.cc
- examples/flutter-external-texture-plugin/flutter_embedder_options.h
- examples/flutter-external-texture-plugin/main.cc
- examples/flutter-video-player-plugin/flutter_embedder_options.h
- examples/flutter-video-player-plugin/main.cc
- examples/flutter-wayland-client/flutter_embedder_options.h
- examples/flutter-wayland-client/main.cc
- examples/flutter-x11-client/flutter_embedder_options.h
- examples/flutter-x11-client/main.cc
- src/client_wrapper/flutter_view_controller.cc
- src/client_wrapper/include/flutter/flutter_view_controller.h
- src/flutter/shell/platform/linux_embedded/flutter_elinux.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.h
- src/flutter/shell/platform/linux_embedded/flutter_elinux_view.cc
- src/flutter/shell/platform/linux_embedded/plugins/settings_plugin.cc
- src/flutter/shell/platform/linux_embedded/plugins/settings_plugin.h
- src/flutter/shell/platform/linux_embedded/public/flutter_elinux.h
This change add "--enable-high-contrast" command-line option to request that UI be rendered with darker colors.
Related issues #2, #168
> accessibility: add --enable-high-contrast option

- src/flutter/shell/platform/linux_embedded/flutter_elinux_view.cc
This change adds a touch pointer state check and increase device id from touch inputs to fix https://github.com/sony/flutter-elinux/issues/126.
```
[FATAL:flutter/lib/ui/window/pointer_data_packet_converter.cc(72)] Check failed: states_.find(pointer_data.device) == states_.end().
```
> touch-input: fix app crashes on any touch input

- src/flutter/shell/platform/common/client_wrapper/include/flutter/event_channel.h
This change fixes the following build error in event_channel.h.
```
/home/hidenori/work/flutter/flutter-elinux-plugins/packages/camera/example/elinux/flutter/ephemeral/cpp_client_wrapper/include/flutter/e vent_channel.h:95:27: error: invalid operands to binary expression ('basic_ostream<char, std::char_traits<char>>' and 'const std::unique_ptr<EncodableValue>')
<< (error->error_details);
^  ~~~~~~~~~~~~~~~~~~~~~~
/home/hidenori/work/flutter/flutter-elinux-plugins/packages/camera/example/elinux/flutter/ephemeral/.plugin_symlinks/camera_elinux/elinu x/channels/event_channel_image_stream.cc:44:18: note: in instantiation of member function 'flutter::EventChannel<>::SetStreamHandler' requested here
event_channel->SetStreamHandler(std::move(event_channel_handler));
^ …
```
> common: fix syntax error in event_channel.h

- src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.h
- src/flutter/shell/platform/linux_embedded/flutter_elinux_view.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux_view.h
- src/flutter/shell/platform/linux_embedded/window/elinux_window.h
- src/flutter/shell/platform/linux_embedded/window/elinux_window_drm.h
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.h
- src/flutter/shell/platform/linux_embedded/window/elinux_window_x11.h
- src/flutter/shell/platform/linux_embedded/window_binding_handler_delegate.h
This change adds notification of display changes to embedder support in Wayland backend.
Fixed #369
> wayland: add notification of display changes to embedder

- CMakeLists.txt
Disable vsync waiter as it may be causing rendering issues.
Related issue (maybe) https://github.com/sony/flutter-elinux/issues/205
> wayland: disable vsync waiter

- .github/workflows/build-test.yml
This change updates actions/checkout version from v2 to v3.
> github-actions: update actions/checkout from v2 to v3

- src/flutter/shell/platform/linux_embedded/plugins/platform_views_plugin.cc
This change fixes a wrong log level setting in platform-views implementation.
> platform-views: fix wrong log level

- src/flutter/shell/platform/linux_embedded/public/flutter_platform_views.h
This change fixes wrong size of texture id.
Related issue: #41
> platform-views: fix wrong size of texture id

- AUTHORS
- src/flutter/shell/platform/linux_embedded/surface/context_egl_stream.cc
- src/flutter/shell/platform/linux_embedded/window/elinux_window_drm.h
- src/flutter/shell/platform/linux_embedded/window/native_window_drm.cc
- src/flutter/shell/platform/linux_embedded/window/native_window_drm.h
Fixed ContextEgl construction for eglstreams. Added support for Nvidia Tegra TX1/TX2
> Fix ContextEgl for EGLStreams. Support Nvidia TX1/2

- src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.cc
Related issue https://github.com/sony/flutter-embedded-linux/issues/334
cc @makotosato-at
> engine: engine: disable fbo_reset_after_present to avoid flicker issues on some H/W

- src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.cc
This reverts commit 6d652df06f94ffd42bd330bde9d77971db92985e.
Related issue #334
> Revert "engine: disable fbo_reset_after_present to avoid flicker issues on some H/W (#385)"

- src/flutter/shell/platform/linux_embedded/surface/elinux_egl_surface.cc
This change disables the partial repaints temporarily because of the flicker issue. Once the root cause in flutter/engine was fixed and its change propagated to the stable channel, this will be lifted up.
See https://github.com/sony/flutter-embedded-linux/issues/334 for the details.
> WAR: temporarily disable partial repaints

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
This change fixes a wrong scale factor logic in configure callback of xdg_toplevel_listener when the scale value is not 1.0.
> wayland: fix wrong scale factor logic in xdg_toplevel_listener

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
This change fixes https://github.com/sony/flutter-embedded-linux/issues/396.
cc @makotosato-at
> wayland: fix wrong xdg_surface buffer size issue

- src/flutter/shell/platform/linux_embedded/surface/context_egl_stream.cc
Hello.
I'm trying to build for armhf.
In the process, I met the following errors.
```
context_egl_stream.cc:31:26: error: non-constant-expression cannot be narrowed from type 'uint32_t' (aka 'unsigned int') to 'EGLAttrib' (aka 'int') in initializer list [-Wc++11-narrowing]
EGL_DRM_PLANE_EXT, static_cast<NativeWindowDrmEglstream*>(window)->PlaneId(),
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
context_egl_stream.cc:31:26: note: insert an explicit cast to silence this issue
EGL_DRM_PLANE_EXT, static_cast<NativeWindowDrmEglstream*>(window)->PlaneId(),
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
static_cast<EGLAttrib>(                                  )
1 error generated.
```
So I added a cast.
> egl_stream: add cast to EGLAttrib

- CMakeLists.txt
This change disables 'dirty-region-management' feature to prevent a fricker issue. See #334 for the details.
> WAR: disable USE_DIRTY_REGION_MANAGEMENT option

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.h
> wayland: fix screen rotation issue on Wayland

- AUTHORS
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
The Wayland text input protocol sends text in
UTF-8 encoding, but the Flutter TextInputModel
expects UTF-16.
This adds the missing conversion from UTF-8 to
UTF-16.
Fixes #414.
> wayland: text input protocol uses UTF-8 encoding

- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
- src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.h
Fix pointer not being drawn on second VNC connect.
Use global_remove event to clean-up seat map.
> Pointer not being drawn on second vnc connection

- AUTHORS
- src/flutter/shell/platform/common/client_wrapper/core_implementations.cc
- src/flutter/shell/platform/common/public/flutter_messenger.h
- src/flutter/shell/platform/linux_embedded/flutter_elinux.cc
This commit adds marshalling of messages sent from native side to be executed on main thread
> Added marshalling to main thread messages sent from native side

- src/flutter/fml/closure.h
- src/flutter/fml/macros.h
- src/flutter/shell/platform/common/client_wrapper/core_implementations.cc
- src/flutter/shell/platform/common/client_wrapper/include/flutter/texture_registrar.h
- src/flutter/shell/platform/common/client_wrapper/texture_registrar_impl.h
- src/flutter/shell/platform/common/public/flutter_texture_registrar.h
- src/flutter/shell/platform/linux_embedded/flutter_elinux.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.h
- src/flutter/shell/platform/linux_embedded/flutter_elinux_texture_registrar.cc
- src/flutter/shell/platform/linux_embedded/flutter_elinux_texture_registrar.h
https://github.com/sony/flutter-embedded-linux/issues/426
> Destroy textures on raster thread

- src/flutter/shell/platform/linux_embedded/flutter_elinux_state.h
types containing std::unique_ptr to incomplete types require a destructor to be defined as the size is unavailable, otherwise the following error is raised at compile time:
```
/usr/lib/gcc/aarch64-linux-gnu/13/../../../../include/c++/13/bits/unique_ptr.h:97:16: error: invalid application of 'sizeof' to an incomplete type 'flutter::FlutterELinuxView'
91 |       _GLIBCXX23_CONSTEXPR
92 |       void
93 |       operator()(_Tp* __ptr) const
|       `- note: in instantiation of member function 'std::default_delete<flutter::FlutterELinuxView>::operator()' requested here
94 |       {
95 | 	static_assert(!is_void<_Tp>::value,
96 | 		      "can't delete pointer to incomplete type");
97 | 	static_assert(sizeof(_Tp)>0,
|                `- error: invalid application of 'sizeof' to an incomplete type …
```
> Ensure FlutterDesktopViewControllerState declares default destructor

- src/flutter/shell/platform/common/client_wrapper/include/flutter/texture_registrar.h
- src/flutter/shell/platform/common/public/flutter_export.h
- src/flutter/shell/platform/common/public/flutter_messenger.h
- src/flutter/shell/platform/common/public/flutter_plugin_registrar.h
- src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.h
- src/flutter/shell/platform/linux_embedded/flutter_elinux_state.h
- src/flutter/shell/platform/linux_embedded/flutter_elinux_texture_registrar.h
- src/flutter/shell/platform/linux_embedded/flutter_elinux_view.h
- src/flutter/shell/platform/linux_embedded/public/flutter_elinux.h
This patch allows the importing of C++ engine APIs into Swift, using the Swift C++ bridging layer.
This fix is useful for [FlutterSwift](https://github.com/PADL/FlutterSwift), and shouldn't be intrusive to non-Swift use cases. I appreciate that this patch lack general utility and I am prepared to maintain a fork if required, but hope you can see the value in merging it.
> Mark FlutterELinuxEngine as an unsafe reference for importing into Swift
