BUILDING-ENGINE-EMBEDDER.md

I fixed typo and added the description of Python 2.

Update readme of building flutter engine

---

README.md

I added the status table of tested devices to README.

Add status table of tested devices

---

README.md

Update status of drm backend on rpi4

---

src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.cc
src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.h

This change is just only for refactoring.

Refactoring some source files in the window directory

---

src/flutter/shell/platform/linux_embedded/surface/native_window_drm.cc
src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.cc
src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.h

I added a check if the process has become a DRM master after opening the DRM device.
If it fails to become a DRM master, the application will terminate.
#15

Add check of DRM master.

---

.github/workflows/build-test.yml
cmake/build.cmake
src/flutter/shell/platform/linux_embedded/surface/linuxes_surface_gl_drm.cc
src/flutter/shell/platform/linux_embedded/surface/linuxes_surface_gl_drm.h
src/flutter/shell/platform/linux_embedded/surface/linuxes_surface_gl_wayland.cc
src/flutter/shell/platform/linux_embedded/surface/linuxes_surface_gl_wayland.h

Changes
- Refactoring: Split source file into .cc and .h files
- Add GitHub Actions for build-test of DRM backend

Refactor source files and add GitHub Actions for build-test of DRM backend 

---

README.md

I updated the tested devices table.

Update README: tested device

---

README.md

I updated the tested devices table, etc.

Update tested devices table

---

examples/README.md
examples/flutter-drm-backend/cmake/user_config.cmake
examples/flutter-external-texture-plugin/cmake/user_config.cmake
examples/flutter-wayland-client/cmake/user_config.cmake
examples/flutter-weston-desktop-shell-virtual-keyboard/cmake/user_config.cmake
examples/flutter-weston-desktop-shell/cmake/user_config.cmake

Update examples README

---

README.md

I've updated README to add the description of x11 and Wayland compositors.

Update README: X11 and Wayland compositors

---

DEBUGGING.md
README.md

Reflect feedbacks https://github.com/sony/flutter-embedded-linux/issues/14

Update README debugging (Reflect feedbacks)

---

src/flutter/shell/platform/embedder/embedder.h

Updated embedder.h to [the latest version](https://github.com/flutter/engine/commit/4a1fd38dbc4a2db946686659e4b461712b66c3ec).

Update embedder.h to the latest version

---

doc/README.md

I updated README in the doc directory a little.
- Format document
- Add description about self-build https://github.com/sony/flutter-embedded-linux/issues/56

Update documents: format and build

---

src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.h

I removed an unnecessary include file.

Remove unnecessary include

---

cmake/build.cmake
src/flutter/shell/platform/linux_embedded/window/native_window_drm.cc
src/flutter/shell/platform/linux_embedded/window/native_window_drm.h
src/flutter/shell/platform/linux_embedded/window/native_window_drm_eglstream.cc
src/flutter/shell/platform/linux_embedded/window/native_window_drm_eglstream.h
src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.cc
src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.h

I fixed the typo of the error log message (https://github.com/sony/flutter-embedded-linux/issues/83). Also, I created .cc file.

Fix drm error message and create .cc file

---

doc/README.md
meta-flutter/README.md

I added the link to meta-flutter in README.

Update README: add a link to meta-flutter

---

README.md
doc/README.md

I added the description about flutter build bundle for debug mode.

Update README: add description of flutter build for debug mode

---

src/flutter/shell/platform/linux_embedded/plugin/key_event_plugin.cc

I fixed https://github.com/sony/flutter-embedded-linux/issues/97

Fix keyboard input bug

---

src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc

Fixed https://github.com/sony/flutter-embedded-linux/issues/105

Fix typo in log message for Wayland

---

doc/README.md
meta-flutter/README.md

Fix typos in READMEs

---

src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc

Fix typo in trace log message for wayland

---

README.md

Update README: objective, features

---

README.md

Update README: RB5 status, etc

---

README.md

Update README: fix tested device table

---

src/flutter/shell/platform/common/engine_switches.cc
src/flutter/shell/platform/common/text_range.h

Merged the latest common source files of Flutter Engine.

Merge flutter engine branch master

---

examples/flutter-drm-eglstream-backend/main.cc
examples/flutter-drm-gbm-backend/main.cc
examples/flutter-external-texture-plugin/main.cc
examples/flutter-wayland-client/main.cc
examples/flutter-weston-desktop-shell-virtual-keyboard/main.cc
examples/flutter-weston-desktop-shell/main.cc
examples/flutter-x11-client/main.cc
src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
src/templates/app/linux-drm/main.cc
src/templates/app/linux-wayland-weston-desktop-shell/main.cc
src/templates/app/linux-wayland/main.cc
src/templates/app/linux-x11/main.cc

Fixed #34, #132 
I'm going to refactor the main loop code...

Fixed bug blocking events from flutter engine for Wayland

---

README.md
doc/README.md

- Added the description about building for Flutter apps
- Updated the table of tested devices

Update README: add description about building for Flutter apps

---

doc/README.md
src/flutter/shell/platform/linux_embedded/logger.cc

See https://github.com/sony/flutter-embedded-linux/issues/134

Add FLUTTER_LOG_LEVELS environment var to change logging levels

---

src/flutter/shell/platform/linux_embedded/flutter_linuxes_engine.cc

I added log output of flutter apps support, which is used to debug by Flutter app developers.

Add log output of flutter apps

---

src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc

Bugfix setting of frame rate for Wayland

---

cmake/build.cmake
src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.cc
src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.h
src/flutter/shell/platform/linux_embedded/logger.cc
src/flutter/shell/platform/linux_embedded/logger.h
src/flutter/shell/platform/linux_embedded/plugin/key_event_plugin.cc
src/flutter/shell/platform/linux_embedded/plugin/lifecycle_plugin.cc
src/flutter/shell/platform/linux_embedded/plugin/lifecycle_plugin.h

I added the lifecycle plugin. But it doesn't be called from anywhere now because we need to consider the specification of the app lifecycle. Also, I added `DEBUG` log level into the logger.

Add lifecycle plugin

---

cmake/build.cmake
src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.cc
src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.h
src/flutter/shell/platform/linux_embedded/plugin/navigation_plugin.cc
src/flutter/shell/platform/linux_embedded/plugin/navigation_plugin.h

I added flutter/navigation plugin support. But it isn't called from anywhere at least now. Also, probably it would be used for the back button only.

Add navigation plugin

---

README.md

Update README: change the order in the document

---

src/flutter/shell/platform/common/client_wrapper/standard_codec.cc
src/flutter/shell/platform/embedder/embedder.h

Merged from:
- https://github.com/flutter/engine/commit/762af4d050bf4051281f49bfe80546483e391f47
- https://github.com/flutter/engine/commit/cc3529093ae0caa15857de385613794365120080

Update cpp shared library and embedder

---

src/flutter/shell/platform/linux_embedded/flutter_linuxes_engine.cc
src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.cc
src/flutter/shell/platform/linux_embedded/flutter_project_bundle.cc
src/flutter/shell/platform/linux_embedded/logger.cc
src/flutter/shell/platform/linux_embedded/logger.h
src/flutter/shell/platform/linux_embedded/plugins/keyboard_glfw_util.cc
src/flutter/shell/platform/linux_embedded/plugins/lifecycle_plugin.cc
src/flutter/shell/platform/linux_embedded/plugins/navigation_plugin.cc
src/flutter/shell/platform/linux_embedded/plugins/platform_views_plugin.cc
src/flutter/shell/platform/linux_embedded/surface/context_egl.cc
src/flutter/shell/platform/linux_embedded/surface/context_egl_stream.cc
src/flutter/shell/platform/linux_embedded/surface/environment_egl.h
src/flutter/shell/platform/linux_embedded/surface/environment_egl_stream.cc
src/flutter/shell/platform/linux_embedded/surface/linuxes_egl_surface.cc
src/flutter/shell/platform/linux_embedded/surface/linuxes_surface.cc
src/flutter/shell/platform/linux_embedded/vsync_waiter.cc
src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.h
src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
src/flutter/shell/platform/linux_embedded/window/linuxes_window_x11.cc
src/flutter/shell/platform/linux_embedded/window/native_window_drm.cc
src/flutter/shell/platform/linux_embedded/window/native_window_drm_eglstream.cc
src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.cc
src/flutter/shell/platform/linux_embedded/window/native_window_wayland.cc
src/flutter/shell/platform/linux_embedded/window/native_window_x11.cc

Replace `LINUXES_LOG` which is the macro name of the logger with `ELINUX_LOG`.

Replace LINUXES_LOG to ELINUX_LOG

---

LICENSE

Fixed the correction leakage of LICENSE file.

Update LICENSE: correction leakage

---

src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.cc

See: https://github.com/sony/flutter-embedded-linux/issues/176

Temporarily disable Vsync callback

---

cmake/build.cmake

I reverted the cmake file to fix a build error in yocto because today's my change broken the yocto building.

Fix build error in yocto

---

cmake/build.cmake
src/flutter/shell/platform/linux_embedded/surface/surface_base.cc
src/flutter/shell/platform/linux_embedded/surface/surface_base.h
src/flutter/shell/platform/linux_embedded/surface/surface_gl.h

Fixed https://github.com/sony/flutter-embedded-linux/issues/182

Rename surface to surface_base

---

src/flutter/shell/platform/common/client_wrapper/include/flutter/event_channel.h

Merged from https://github.com/flutter/engine/commit/c2bd0a25c7e2bd1914246b82ed898282dad32ee0

Update common cpp library to the latest version (06/25/2021)

---

examples/flutter-video-player-plugin/README.md
examples/flutter-video-player-plugin/cmake/user_build.cmake
examples/flutter-video-player-plugin/cmake/user_config.cmake
examples/flutter-video-player-plugin/command_options.h
examples/flutter-video-player-plugin/flutter/generated_plugin_registrant.cc
examples/flutter-video-player-plugin/flutter/generated_plugin_registrant.h
examples/flutter-video-player-plugin/flutter/generated_plugins.cmake
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/CMakeLists.txt
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/gst_video_player.cc
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/gst_video_player.h
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/include/video_player/video_player_plugin.h
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/messages/create_message.h
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/messages/looping_message.h
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/messages/messages.h
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/messages/mix_with_others_message.h
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/messages/playback_speed_message.h
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/messages/position_message.h
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/messages/texture_message.h
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/messages/volume_message.h
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/video_player_plugin.cc
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/video_player_stream_handler.h
examples/flutter-video-player-plugin/flutter/plugins/video_player/elinux/video_player_stream_handler_impl.h
examples/flutter-video-player-plugin/flutter_window.cc
examples/flutter-video-player-plugin/flutter_window.h
examples/flutter-video-player-plugin/main.cc

I created a flutter plugin for video player. This plugin uses GStreamer internally and is compatible with [the Flutter official video player plugin](https://github.com/flutter/plugins/tree/master/packages/video_player/video_player). Also, this plugin is temporarily putting here and there are still some bugs. I am going to be moved to another new repo soon.
- https://github.com/sony/flutter-embedded-linux/issues/174

Add video player plugin using GStreamer

---

src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc

I fixed the timing of calling `wp_presentation_feedback_add_listener` because the current implementation is not correct, and sometimes apps crashed.

Fix the timing of calling wp_presentation_feedback_add_listener

---

examples/README.md

Update examples readme: add video player plugin

---

src/flutter/shell/platform/linux_embedded/logger.h

I added define macro (compiler option) to ignore log messages.

Add compiler option to ignore log messages

---

CMakeLists.txt
cmake/build.cmake
src/flutter/shell/platform/linux_embedded/logger.h

I added `ENABLE_ELINUX_EMBEDDER_LOG` compiler option.

Add ENABLE_ELINUX_EMBEDDER_LOG compiler option

---

src/flutter/shell/platform/common/client_wrapper/standard_codec.cc

Merged from https://github.com/flutter/engine/commit/39f9a27ef57262102cba5bbadde958686a238e38

Merge common-cpp-library from flutter/engine repo (07262021)

---

README.md

- Added the image of elinux's software stack
- Added the link to flutter-elinux

Update README: add software stack image of elinux embedder

---

src/flutter/shell/platform/linux_embedded/plugins/keyboard_glfw_util.cc

Remove duplicate include in keyboard_glfw_util.cc.

Refactoring: remove duplicate include

---

src/flutter/shell/platform/embedder/embedder.h

Merged from https://github.com/flutter/engine/commit/0112d4b422de28dba00505df4c1f84846a6b75ec#diff-06f2c0a6c7bb5df337492f6d661883b12f847d1677220bd7dd7add48a78784c5

Merge the latest embedder header from flutter/engine

---

src/flutter/shell/platform/common/client_wrapper/include/flutter/encodable_value.h

Merged from https://github.com/flutter/engine/commit/cc3529093ae0caa15857de385613794365120080#diff-b751ee972d196d9d78adb28211809428af5875890719ed63f76980b57430fca8

Merge the latest common cpp source files from flutter/engine

---

src/flutter/shell/platform/common/client_wrapper/include/flutter/encodable_value.h
src/flutter/shell/platform/common/client_wrapper/include/flutter/engine_method_result.h
src/flutter/shell/platform/common/client_wrapper/include/flutter/texture_registrar.h
src/flutter/shell/platform/common/client_wrapper/standard_codec.cc

Merged from
- flutter/engine@eac4cd2
- https://github.com/flutter/engine/commit/29ea28d67b2d4c9cad0add3cfb9d0c6171146aa1

Merge common shared cpp source files 11/25/2021

---

src/flutter/shell/platform/linux_embedded/window/elinux_window_drm.h

Fixed https://github.com/sony/flutter-embedded-linux/issues/237
cc @Taha-Firoz

[drm] Fix: mouse cursor is visible even when no mouse is connected

---

src/flutter/shell/platform/embedder/embedder.h

Merge the latest embedder (v.2.8.0)

---

src/flutter/shell/platform/embedder/embedder.h

Merged the latest `embedder.h` from https://github.com/flutter/engine/commit/6c67716b081a3614305f99b4e6ade2562f974fee

merge embedder.h from flutter/engine

---

src/flutter/shell/platform/embedder/embedder.h

Merged the latest embedder.h from https://github.com/flutter/engine/commit/5f2b5660f2551a60021b66cfd267abc2aa97bfec

Merged the latest embedder.h from flutter/engine (04/07/2022)

---

src/flutter/shell/platform/linux_embedded/window/elinux_window_drm.h
src/flutter/shell/platform/linux_embedded/window/native_window_drm.cc
src/flutter/shell/platform/linux_embedded/window/native_window_drm.h
src/flutter/shell/platform/linux_embedded/window/native_window_drm_eglstream.cc
src/flutter/shell/platform/linux_embedded/window/native_window_drm_eglstream.h
src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.cc
src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.h

Fixed https://github.com/sony/flutter-embedded-linux/issues/256

Fix drm backends rotation option bug

---

README.md

Hi folks, 
thanks for bringing flutter to the raspberry pi! I use it for a hobby project. 
It works even on the pi3 model B (requires to use swapfile due to limited memory). 
Just wanted to let you know :)

Updated Supported platforms (README) 

---

src/flutter/shell/platform/embedder/embedder.h

Merge the latest changes in embedder from https://github.com/flutter/engine/commit/8286098c6311d6bd2b8fd5fd9ec7ba3ca0c250ce

Update embedder header file

---

src/flutter/shell/platform/linux_embedded/public/flutter_elinux.h

Merge https://github.com/flutter/engine/commit/ccf6cee766f412f9920b8fa090b83050cebb4962

[Merge] Fix incorrect public C API argument type

---

CMakeLists.txt
cmake/build.cmake
src/flutter/shell/platform/linux_embedded/surface/context_egl.cc

Add egl alpha component of the color buffer option

---

src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc

Update versions of the wayland protocols correctly

---

AUTHORS
examples/flutter-drm-eglstream-backend/command_options.h
examples/flutter-drm-eglstream-backend/flutter_embedder_options.h
examples/flutter-drm-eglstream-backend/main.cc
examples/flutter-drm-gbm-backend/command_options.h
examples/flutter-drm-gbm-backend/flutter_embedder_options.h
examples/flutter-drm-gbm-backend/main.cc
examples/flutter-external-texture-plugin/command_options.h
examples/flutter-external-texture-plugin/flutter_embedder_options.h
examples/flutter-external-texture-plugin/main.cc
examples/flutter-video-player-plugin/command_options.h
examples/flutter-video-player-plugin/flutter_embedder_options.h
examples/flutter-video-player-plugin/main.cc
examples/flutter-wayland-client/command_options.h
examples/flutter-wayland-client/flutter_embedder_options.h
examples/flutter-wayland-client/main.cc
examples/flutter-x11-client/command_options.h
examples/flutter-x11-client/flutter_embedder_options.h
examples/flutter-x11-client/main.cc
src/client_wrapper/flutter_view_controller.cc
src/client_wrapper/include/flutter/flutter_view_controller.h
src/flutter/shell/platform/linux_embedded/public/flutter_elinux.h
src/flutter/shell/platform/linux_embedded/window/elinux_window_drm.h
src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
src/flutter/shell/platform/linux_embedded/window/elinux_window_x11.cc

This adds support for manually specifying dpi scale factor. `--force-scale-factor` argument is added to examples to set factor. Tested on wayland.

Add support for setting scale factor from parameters

---

examples/flutter-drm-eglstream-backend/command_options.h
examples/flutter-drm-gbm-backend/command_options.h
examples/flutter-external-texture-plugin/command_options.h
examples/flutter-video-player-plugin/command_options.h
examples/flutter-wayland-client/command_options.h
examples/flutter-x11-client/command_options.h

Remove unnecessary comments

---

src/flutter/shell/platform/linux_embedded/window/elinux_window_drm.h

Fixed https://github.com/sony/flutter-elinux/issues/143

drm: add multiple dri cards support using FLUTTER_DRM_DEVIE env

---

src/flutter/shell/platform/linux_embedded/flutter_elinux_view.h

Fix uninitialized var for touch_events

---

src/client_wrapper/flutter_view_controller.cc
src/flutter/shell/platform/linux_embedded/flutter_elinux_view.cc

Fix code format check errors

---

examples/flutter-drm-eglstream-backend/flutter_embedder_options.h
examples/flutter-drm-gbm-backend/flutter_embedder_options.h
examples/flutter-external-texture-plugin/flutter_embedder_options.h
examples/flutter-video-player-plugin/flutter_embedder_options.h
examples/flutter-wayland-client/flutter_embedder_options.h
examples/flutter-x11-client/flutter_embedder_options.h

X11/DRM: fixed crash due to unsupported args reference

---

examples/flutter-drm-eglstream-backend/flutter_embedder_options.h
examples/flutter-drm-gbm-backend/flutter_embedder_options.h
examples/flutter-external-texture-plugin/flutter_embedder_options.h
examples/flutter-video-player-plugin/flutter_embedder_options.h
examples/flutter-wayland-client/flutter_embedder_options.h
examples/flutter-x11-client/flutter_embedder_options.h
src/flutter/shell/platform/linux_embedded/window/elinux_window_x11.cc
src/flutter/shell/platform/linux_embedded/window/native_window_x11.cc
src/flutter/shell/platform/linux_embedded/window/native_window_x11.h

Add x11 window title support

---

src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.h

wayland: fix "xdg_surface has never been configured" error

---

src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc

Fixed https://github.com/sony/flutter-elinux/issues/176

wayland: add window size clipping

---

src/flutter/shell/platform/embedder/embedder.h

From https://github.com/flutter/engine/commit/ce7be0093399666e80f0431b45d5416bdd6ccf6a

embedder: update embedder's header file

---

README.md

This change moves the description related to tested devices to Wiki.

readme: remove description related to tested devices

---

src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc

wayland: fix fullscreen not working on Wayland

---

src/flutter/shell/platform/common/engine_switches.cc
src/flutter/shell/platform/linux_embedded/flutter_elinux.cc
src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.cc
src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.h
src/flutter/shell/platform/linux_embedded/flutter_elinux_view.cc
src/flutter/shell/platform/linux_embedded/flutter_project_bundle.cc
src/flutter/shell/platform/linux_embedded/flutter_project_bundle.h
src/flutter/shell/platform/linux_embedded/surface/context_egl.cc
src/flutter/shell/platform/linux_embedded/surface/context_egl.h
src/flutter/shell/platform/linux_embedded/window/elinux_window_drm.h
src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.h
src/flutter/shell/platform/linux_embedded/window/elinux_window_x11.cc
src/flutter/shell/platform/linux_embedded/window/elinux_window_x11.h
src/flutter/shell/platform/linux_embedded/window/native_window_drm.h
src/flutter/shell/platform/linux_embedded/window/native_window_drm_eglstream.cc
src/flutter/shell/platform/linux_embedded/window/native_window_drm_eglstream.h
src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.cc
src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.h
src/flutter/shell/platform/linux_embedded/window/renderer/window_decorations_wayland.cc
src/flutter/shell/platform/linux_embedded/window/renderer/window_decorations_wayland.h
src/flutter/shell/platform/linux_embedded/window_binding_handler.h

impeller: add impeller initial implementation

---

cmake/build.cmake
src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.h

I've tested this change on Sway.
Fixed #216

wayland: add xdg-decoration support

---

src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.cc

wayland: delete old todo comment for vsync

---

src/flutter/shell/platform/common/client_wrapper/include/flutter/encodable_value.h
src/flutter/shell/platform/common/client_wrapper/include/flutter/event_channel.h
src/flutter/shell/platform/common/client_wrapper/include/flutter/event_stream_handler.h
src/flutter/shell/platform/common/client_wrapper/include/flutter/method_channel.h
src/flutter/shell/platform/common/client_wrapper/include/flutter/plugin_registrar.h
src/flutter/shell/platform/common/client_wrapper/standard_codec.cc

Merged the latest source files from flutter/engine repo.
* src/flutter/shell/platform/common/client_wrapper/include/flutter/encodable_value.h
=> https://github.com/flutter/engine/commit/a3c5a319fccb7b137949ee7f410bf2510148dd3d
* src/flutter/shell/platform/common/client_wrapper/include/flutter/event_channel.h
src/flutter/shell/platform/common/client_wrapper/include/flutter/event_stream_handler.h
=> https://github.com/flutter/engine/commit/52574efd2a88390575423b6407ffd13a39f58429
* src/flutter/shell/platform/common/client_wrapper/include/flutter/method_channel.h
=> https://github.com/flutter/engine/commit/4165d4b9b6f1843e91ccbf13a4c12a32d48ca648
* src/flutter/shell/platform/common/client_wrapper/include/flutter/plugin_registrar.h
=> …

client_wrapper: merge common/client_wrapper

---

src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc

This change adds trace level logs to improve logging and debuggability.

wayland: add trace level logs to wayland listeners

---

src/flutter/shell/platform/linux_embedded/plugins/lifecycle_plugin.cc
src/flutter/shell/platform/linux_embedded/plugins/lifecycle_plugin.h

This change adds a new state hidden to lifecycle plugin.

lifecycle_plugin: add hidden state

---

src/flutter/shell/platform/linux_embedded/plugins/platform_views_plugin.cc
src/flutter/shell/platform/linux_embedded/plugins/platform_views_plugin.h
src/flutter/shell/platform/linux_embedded/public/flutter_platform_views.h

platform-views: implement more APIs in platform views

---

src/flutter/shell/platform/linux_embedded/window/elinux_window_x11.cc
src/flutter/shell/platform/linux_embedded/window/native_window_x11.cc
src/flutter/shell/platform/linux_embedded/window/native_window_x11.h

This change adds fullscreen option support.
Related issues:
- https://github.com/sony/flutter-embedded-linux/issues/37
- https://github.com/sony/flutter-elinux/issues/136

x11: support fullscreen option

---

src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.cc
src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc

engine: add text_scaling_factor option value check

---

src/flutter/shell/platform/embedder/embedder.h

Merged from https://github.com/flutter/engine/commit/f358bde6ce0e54bd5eb5fc6e2910d291b7578548

embedder: merge embedder.h from flutter/engine

---

src/flutter/shell/platform/linux_embedded/surface/elinux_egl_surface.cc

This reverts commit 820ee198b3a888cbe9dd06a9fffb3930c7166fc0.
Related issue #334

Revert "WAR: temporarily disable partial repaints (#388)"

---

src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc

Fixes issue #403 .
I agree to delegate all rights related to this change to Sony.

Fixes issue #403: Segmentation fault when updating destroyed mouse pointer

---

src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc

wayland: fix wp_presentation_feedback leak

---

AUTHORS
src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.h

Added the ability to have multiple seats, this allows f.e. weston screenshare and a local touch input to work at the same time.

Multiple seats

---

src/flutter/shell/platform/common/client_wrapper/core_implementations.cc

@HidenoriMatsubayashi  Fix after merge of issue 421 - had disabled check in CMake of app, thus haven't seen

Removed unused variable

---

src/flutter/shell/platform/linux_embedded/flutter_elinux_engine.cc
src/flutter/shell/platform/linux_embedded/plugins/platform_views_plugin.cc
src/flutter/shell/platform/linux_embedded/surface/context_egl.cc
src/flutter/shell/platform/linux_embedded/window/elinux_window_drm.h
src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc
src/flutter/shell/platform/linux_embedded/window/native_window.h

This change fixes the CI failure due to code format warnings.

linux_embedded: fix github actions' failure
